name: native_updater
description: Flutter package for prompting users to update with a native dialog whether using the app store version or any version at the user's discretion.

version: 0.1.9
homepage: https://github.com/ofload/native_updater

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  assets:
    - packages/native_updater/images/google_play.png
